app/config/ConfigKeys.scala, app/config/features/Features.scala, app/testOnly/controllers/FeatureSwitchController.scala, app/testOnly/forms/FeatureSwitchForm.scala, app/testOnly/models/FeatureSwitchModel.scala, app/testOnly/views/featureSwitch.scala.html, conf/application.conf
AppConfigProd PR: https://github.com/hmrc/app-config-production/pull/2860
=> [MSCC-105] Added new Feature Switch for New Filter View enabled

app/controllers/SoftwareChoicesController.scala, app/models/SoftwareChoicesFilterViewModel.scala, app/views/software_choices_filter.scala.html, app/views/templates/provider_table_template.scala.html, app/views/templates/result_count_template.scala.html, conf/messages, public/javascript/dynamicFilterSearch.js, test/assets/messages/CommonMessages.scala, test/assets/messages/FilterSearchMessages.scala, test/models/SoftwareChoicesFilterViewModelSpec.scala, test/views/SoftwareChoicesFilterViewSpec.scala, test/views/templates/ResultCountTemplateViewSpec.scala
Also some minor accessibility tweaks:
- AJAX call is only submitted on change of data within the input field - rather than keypress
- Added `aria-live="polite"` metadata tag to the result count so that this is reread to screen readers
- Result count is only shown if at least one filter OR a search term exists.
=> [MSCC-127] Changes to reflect v0.21.0 of prototype

conf/SoftwareProviders.json, test/resources/TestSoftwareProviders.json
The following entries are missing so haven't been updated:
Comet Scientific Software
John Hemming
Osrec
=> SAR-5165 - Adding free filter to relevant software

conf/SoftwareProviders.json, test/resources/TestSoftwareProviders.json
Updated SoftwareChoices Vendor List and related tests to match updated list.
=> SAR-5396 - Updated SoftwareChoices Vendor List

conf/SoftwareProviders.json, test/resources/TestSoftwareProviders.json
Software Choices providers update
=> SAR-5775 Software Choices providers update

project/AppDependencies.scala, project/plugins.sbt
Updated Software Choices Frontend dependencies
=> SAR-5815 Updated Software Choices Frontend dependencies

app/views/accessibility_statement.scala.html, conf/messages.cy, conf/messages.en, test/views/AccessibilityStatementViewSpec.scala
SAR-5872 Updated content for the fully compliant accessibility statement
=> SAR-5872 Updated content for the fully compliant accessibility statement

app/config/ConfigKeys.scala, app/config/features/Features.scala, app/testOnly/controllers/FeatureSwitchController.scala, app/testOnly/forms/FeatureSwitchForm.scala, app/testOnly/models/FeatureSwitchModel.scala, app/testOnly/views/featureSwitch.scala.html, app/views/software_choices_filter.scala.html, conf/application.conf, test/config/mocks/MockAppConfig.scala, test/utils/TestUtils.scala
Show Agent/Business Filter
Show Additional Software Filter
Show Type of Software Filter
Show Accessibility Filter
Removed
=> SAR-5939 Removal of filter feature switches

conf/SoftwareProviders.json, test/resources/TestSoftwareProviders.json
Reverts hmrc/software-choices-frontend#318
=> Revert "DL-14372 : Adding New Vendor"

conf/SoftwareProviders.json, test/resources/TestSoftwareProviders.json
Reverts hmrc/software-choices-frontend#319
=> DL-14372 : Adding New Vendor

conf/SoftwareProviders.json, test/resources/TestSoftwareProviders.json
=> DL-14517 : Remove Floral Frog from companies list

README.md, conf/SoftwareProviders.json, test/resources/TestSoftwareProviders.json
TICKET: https://jira.tools.tax.service.gov.uk/browse/DL-14669
=> DL-14669 add a new vendor

conf/SoftwareProviders.json, test/resources/TestSoftwareProviders.json
=> DL-14722: New Vendor added

conf/SoftwareProviders.json, test/resources/TestSoftwareProviders.json
=> remove vendor DL-14873

conf/SoftwareProviders.json, conf/application.conf, test/resources/TestSoftwareProviders.json
ticket link: https://jira.tools.tax.service.gov.uk/browse/DL-15335
=> DL-15335 add a vendor

conf/SoftwareProviders.json, test/resources/TestSoftwareProviders.json
https://jira.tools.tax.service.gov.uk/browse/DL-15666
=> DL-15666 add a new vendor

conf/SoftwareProviders.json, test/resources/TestSoftwareProviders.json
Ticket 1: https://jira.tools.tax.service.gov.uk/browse/DL-15702
Ticket 2: https://jira.tools.tax.service.gov.uk/browse/DL-15703
=> DL-15702 & DL-15703

conf/SoftwareProviders.json, test/resources/TestSoftwareProviders.json
=> DL-15883 add a new vendor

conf/SoftwareProviders.json, test/resources/TestSoftwareProviders.json
=> DL-15965 add new vendor

app/views/software_choices_filter.scala.html, conf/messages.en, test/assets/messages/FilterSearchMessages.scala, test/views/SoftwareChoicesFilterViewSpec.scala
=> [DL-14223] Add bold warning text to main search page
